export const theme = {
  colors: {
    primary: '#0F766E',
    primaryLight: '#14B8A6',
    primarySoft: '#CCFBF1',
    textMain: '#0F172A',
    textSecondary: '#475569',
    background: '#FFFFFF',
    surface: '#F8FAFC',
    pinColor: '#DC2626',
    accessPublicBg: '#DCFCE7',
    accessPublicText: '#166534',
    accessPaidBg: '#FEF3C7',
    accessPaidText: '#92400E',
    accessPermitBg: '#DBEAFE',
    accessPermitText: '#1E40AF',
    accessPrivateBg: '#FEE2E2',
    accessPrivateText: '#991B1B',
    border: '#E2E8F0',
    muted: '#CBD5E1',
    danger: '#DC2626',
    warning: '#CA8A04',
    success: '#16A34A',
  },
  fonts: {
    heading: 'Georgia',
    body: 'System',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 12,
    lg: 20,
    full: 9999,
  },
} as const;
